#!/usr/bin/env python3
"""Regenerate the `-o` option tables in the driver READMEs from `catalog --json`.

Documentation tooling for this repository, not part of any published package —
which is why it lives in ``scripts/`` rather than beside the SDK it reads from.

The tables say what every device accepts, which is exactly the information the SDKs
already carry as data (RFC 0003 §5) — so they are generated rather than typed, and
cannot fall behind the code the way a hand-written list does. The table in
``qpi-driver/py/README.md`` is the one that exists today; the marked block is the
whole contract, so a second README can opt in by adding one.

Reads the catalog on stdin and rewrites the block between::

    <!-- catalog:begin -->
    <!-- catalog:end -->

in each file named on the command line. Nothing calls it directly — run
``make sync-driver-catalog``, which produces the catalog it reads and then runs it
over every README that has the markers.
"""

import json
import sys
from pathlib import Path

BEGIN = "<!-- catalog:begin -->"
END = "<!-- catalog:end -->"


def requirement(option: dict) -> str:
    """Whether an option must be given, and what it falls back to if not."""
    if option["required"]:
        return "**required**"
    if option["default"]:
        return f"`{option['default']}`"
    return "—"


def render(catalog: dict) -> str:
    """The generated block: the devices, then their options.

    Devices sharing an option schema — every ``process`` device does, being the same
    driver over a different executor — share one options table rather than repeating
    it five times.
    """
    lines = [
        BEGIN,
        "",
        "<!-- Generated by `make sync-driver-catalog`. Do not edit by hand. -->",
        "",
        "| Operation | Device | Ships with |",
        "|-----------|--------|------------|",
    ]

    schemas: dict[str, tuple[list[dict], list[str]]] = {}
    for operation in catalog["operations"]:
        for device in operation["devices"]:
            extra = f"`{device['extra']}`" if device["extra"] else "base `[cli]`"
            lines.append(f"| `{operation['name']}` | `{device['name']}` | {extra} |")
            key = json.dumps([o["key"] for o in device["options"]])
            schemas.setdefault(key, (device["options"], []))[1].append(
                f"`{device['name']}`"
            )

    for options, owners in schemas.values():
        if not options:
            continue
        lines.extend(
            [
                "",
                f"`-o` options for {', '.join(owners)}:",
                "",
                "| Option | Type | Default | Description |",
                "|--------|------|---------|-------------|",
            ]
        )
        for option in options:
            lines.append(
                f"| `{option['key']}` | `{option['type']}` | "
                f"{requirement(option)} | {option['help']} |"
            )

    lines.extend(["", END])
    return "\n".join(lines)


def main() -> int:
    catalog = json.load(sys.stdin)
    block = render(catalog)

    for name in sys.argv[1:]:
        path = Path(name)
        text = path.read_text()
        if BEGIN not in text or END not in text:
            print(f"{path}: no catalog markers; skipping", file=sys.stderr)
            continue
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        path.write_text(text[:start] + block + text[end:])
        print(f"{path}: catalog table regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
